#!/bin/bash -e
# Initialise the snap upon install

# Create file spool
rm -Rf "${SNAP_COMMON}/spool"
mkdir -m 0700 "${SNAP_COMMON}/spool"

# Initial ACL rules
cat <<EOF > "${SNAP_COMMON}/config.yaml"
http-proxy:
  policy: allow
  rules:
    - dst: [
      ]
      access: deny
EOF
