#!/bin/bash -e
# Initialise the snap upon install

ACL_YAML="${SNAP_DATA}/conf/acl.yaml"

# Create file spool
rm -Rf "${SNAP_COMMON}/spool"
mkdir -m 0700 "${SNAP_COMMON}/spool"

# Initial ACL rules
mkdir -p $(dirname "$ACL_YAML")
cp "${SNAP}/skel/acl.yaml" "$ACL_YAML"
