#!/bin/bash -e

ACL_YAML="${SNAP_DATA}/conf/acl.yaml"

[ -f "$ACL_YAML" ] && exit 0

mkdir -p $(dirname "$ACL_YAML")

# If old acl configuration exists, move it to conf/
if [ -f "${SNAP_DATA}/acl.yaml" ]; then
	mv "${SNAP_DATA}/acl.yaml" "$ACL_YAML"
fi

# Create an acl file if it doesn't exist
if [ ! -f "$ACL_YAML" ]; then
	cp "${SNAP}/skel/acl.yaml" "$ACL_YAML"
fi
